# People (fallbacks if no route matches)
content_developers:
  - alexclowe            # GitHub usernames (assignable)
cd_managers:
  - alexclowe      # usernames or team slugs like org/team (mentioned, not assigned)

# Labels & timing
labels:
  triage: "B36B00"
  overdue: "D93F0B"
status_in_progress_label: "status:in-progress"

# Follow-up window
followup_days: 7         # e.g., 10

# Per-folder routing rules (first match wins; GLOB patterns)
routes:
  - pattern: "docs/getting-started/**"
    content_developers:
      - alexclowe
    cd_managers:
      - msft-cd-manager
  - pattern: "guides/**"
    content_developers:
      - another-user
    cd_managers:
      - msft-cd-manager2
  # default fallback uses top-level content_developers and cd_managers

