# People
content_developers:
  - alexclowe            # default assignees if no route match
cd_managers:
  - alexclowe

# Labels & timing
labels:
  triage: "B36B00"
  overdue: "D93F0B"       # color for the overdue label
status_in_progress_label: "status:in-progress"

# Follow-up timing
followup_days: 7           # change to 10, 14, etc.

# Per-folder routing rules (first match wins; GLOB patterns)
# If the issue body (or template field) mentions a matching path, assign these CDs instead.
routes:
  - pattern: "/**"
    content_developers:
      - alexclowe
  #- pattern: "guides/**"
  #  content_developers:
  #    - another-user
  # default falls back to content_developers above
